services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eventstech
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: